#define ZERO_BYTES  0
#define ONE_BYTE    1
#define TWO_BYTES   2
#define THREE_BYTES 3
#define FOUR_BYTES  4
#define FIVE_BYTES  5
#define SIX_BYTES   6 
#define SEVEN_BYTES 7
#define EIGHT_BYTES 8
#define INIT_BYTE   0